/**
 * NextGen CMA — Email Service
 *
 * Handles SMTP configuration, admin notification dispatching,
 * and automated visitor acknowledgements using Nodemailer.
 */

import nodemailer from 'nodemailer';

// Helper to determine if SMTP configuration is fully provided
const isSmtpConfigured = () => {
  return (
    process.env.SMTP_HOST &&
    process.env.SMTP_PORT &&
    process.env.SMTP_USER &&
    process.env.SMTP_PASS &&
    process.env.ADMIN_EMAIL
  );
};

// Create a transient transport utility
const getTransporter = () => {
  if (!isSmtpConfigured()) {
    return null;
  }

  return nodemailer.createTransport({
    host: process.env.SMTP_HOST,
    port: parseInt(process.env.SMTP_PORT, 10) || 587,
    secure: parseInt(process.env.SMTP_PORT, 10) === 465, // true for 465, false for other ports
    auth: {
      user: process.env.SMTP_USER,
      pass: process.env.SMTP_PASS,
    },
  });
};

/**
 * Dispatch notification email to Platform Admin.
 * @param {object} messageData - The contact form submission content.
 */
export const sendAdminNotification = async (messageData) => {
  const { name, email, phone, subject, message } = messageData;

  if (!isSmtpConfigured()) {
    console.warn(
      '⚠️ SMTP is not fully configured. Skipping Admin Notification email dispatch. Ensure SMTP_HOST, SMTP_PORT, SMTP_USER, SMTP_PASS, and ADMIN_EMAIL are set.'
    );
    return;
  }

  try {
    const transporter = getTransporter();
    const adminEmail = process.env.ADMIN_EMAIL;

    const mailOptions = {
      from: `"NextGen CMA Portal" <${process.env.SMTP_USER}>`,
      to: adminEmail,
      subject: `[New Inquiry] ${subject}`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
          <h2 style="color: #cda250; border-bottom: 2px solid #805ad5; padding-bottom: 10px;">New Contact Submission Received</h2>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr>
              <td style="padding: 8px; font-weight: bold; width: 120px;">Name:</td>
              <td style="padding: 8px;">${name}</td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold;">Email:</td>
              <td style="padding: 8px;"><a href="mailto:${email}">${email}</a></td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold;">Phone:</td>
              <td style="padding: 8px;">${phone}</td>
            </tr>
            <tr>
              <td style="padding: 8px; font-weight: bold;">Subject:</td>
              <td style="padding: 8px;">${subject}</td>
            </tr>
          </table>
          <div style="margin-top: 20px; padding: 15px; background-color: #f7fafc; border-left: 4px solid #805ad5; border-radius: 4px;">
            <h3 style="margin-top: 0; color: #4a5568;">Message Body:</h3>
            <p style="white-space: pre-wrap; color: #2d3748; line-height: 1.6; margin-bottom: 0;">${message}</p>
          </div>
          <p style="margin-top: 25px; font-size: 11px; color: #a0aec0; text-align: center;">
            This email was automatically generated by the NextGen CMA Platform.
          </p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`✉️ Admin notification email sent successfully: ${info.messageId}`);
  } catch (error) {
    console.error('❌ Failed to dispatch admin notification email:', error);
  }
};

/**
 * Send automated acknowledgement email back to the visitor.
 * @param {object} messageData - The contact form submission content.
 */
export const sendVisitorAcknowledgement = async (messageData) => {
  const { name, email, subject } = messageData;

  if (!isSmtpConfigured()) {
    console.warn(
      '⚠️ SMTP is not fully configured. Skipping Visitor Acknowledgement email dispatch.'
    );
    return;
  }

  try {
    const transporter = getTransporter();

    const mailOptions = {
      from: `"NextGen CMA Team" <${process.env.SMTP_USER}>`,
      to: email,
      subject: `Acknowledgement: We received your query regarding "${subject}"`,
      html: `
        <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #e0e0e0; border-radius: 8px;">
          <h2 style="color: #805ad5; text-align: center;">Thank You for Contacting NextGen CMA</h2>
          <p style="color: #2d3748; font-size: 15px; line-height: 1.6;">Hello <strong>${name}</strong>,</p>
          <p style="color: #2d3748; font-size: 14px; line-height: 1.6;">
            We have successfully received your inquiry about "<strong>${subject}</strong>". 
            Our counselors and expert professionals are reviewing your message and will get back to you within 24 business hours.
          </p>
          <div style="margin: 25px 0; text-align: center;">
            <p style="font-size: 12px; color: #718096; margin-bottom: 12px;">In the meantime, you can join our online candidate communities:</p>
            <a href="https://chat.whatsapp.com/EG1Xfx2JylM0SISodwhLh2?s=cl&p=a&ilr=0" style="background-color: #25D366; color: white; padding: 10px 18px; border-radius: 5px; text-decoration: none; font-weight: bold; margin-right: 10px; display: inline-block;">WhatsApp Community</a>
            <a href="https://t.me/nextgencma18" style="background-color: #0088cc; color: white; padding: 10px 18px; border-radius: 5px; text-decoration: none; font-weight: bold; display: inline-block;">Telegram Channel</a>
          </div>
          <p style="color: #2d3748; font-size: 14px; line-height: 1.6;">
            Best Regards,<br />
            <strong>NextGen CMA Support Team</strong>
          </p>
          <hr style="border: 0; border-top: 1px solid #e2e8f0; margin: 20px 0;" />
          <p style="font-size: 11px; color: #a0aec0; text-align: center;">
            Please do not reply directly to this automated email. For additional assistance, contact our official helpdesk at nextgencma18@gmail.com.
          </p>
        </div>
      `,
    };

    const info = await transporter.sendMail(mailOptions);
    console.log(`✉️ Visitor acknowledgement email sent successfully: ${info.messageId}`);
  } catch (error) {
    console.error('❌ Failed to dispatch visitor acknowledgement email:', error);
  }
};
